name: Check Java Format

on: [ push, pull_request ]

permissions:
  contents: read

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit
      - name: Checkout repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - uses: axel-op/googlejavaformat-action@b8a3003f6bb1d4b521a2105f35a16131d49a8709 # v3.6
        with:
          args: "--aosp --skip-javadoc-formatting --skip-reflowing-long-strings --skip-sorting-imports --replace"
          skip-commit: true
      - name: Print diffs
        run: git --no-pager diff --exit-code